
provider tencentcloud {
  region = local.region
}

//+ ap-bangkok         = "Southeast Asia(Bangkok)"
//+ ap-beijing         = "North China region(Beijing)"
//+ ap-beijing-fsi     = "North China region(Beijing Finance)"
//+ ap-changsha-ec     = "Central China(Changsha)"
//+ ap-chengdu         = "Southwest China(Chengdu)"
//+ ap-chongqing       = "Southwest China(Chongqing)"
//+ ap-fuzhou-ec       = "East China(Fuzhou)"
//+ ap-guangzhou       = "South China(Guangzhou)"
//+ ap-guangzhou-open  = "South China(Guangzhou OPEN)"
//+ ap-hangzhou-ec     = "East China(Hangzhou)"
//+ ap-hefei-ec        = "East China(Hefei)"
//+ ap-hongkong        = "Hong Kong, Macau and Taiwan (China)(Hong Kong, China)"
//+ ap-jakarta         = "Southeast Asia(Jakarta)"
//+ ap-jinan-ec        = "East China(Jinan)"
//+ ap-mumbai          = "South Asia(Mumbai)"
//+ ap-nanjing         = "East China(Nanjing)"
//+ ap-qingyuan        = "South China(Qingyuan)"
//+ ap-seoul           = "Northeast Asia(Seoul)"
//+ ap-shanghai        = "East China(Shanghai)"
//+ ap-shanghai-fsi    = "East China(Shanghai Finance)"
//+ ap-shenyang-ec     = "Northeast China(Shenyang)"
//+ ap-shenzhen-fsi    = "South China(Shenzhen Finance)"
//+ ap-shijiazhuang-ec = "North China region(Shijiazhuang)"
//+ ap-singapore       = "Southeast Asia(Singapore)"
//+ ap-taipei          = "Hong Kong, Macau and Taiwan (China)(Chinese Taipei)"
//+ ap-tokyo           = "Northeast Asia(Tokyo)"
//+ ap-wuhan-ec        = "Central China(Wuhan)"
//+ ap-xian-ec         = "Northwest region(Xi'an)"
//+ ap-zhengzhou-ec    = "Central China(Zhengzhou)"
//+ eu-frankfurt       = "Europe(Frankfurt)"
//+ eu-moscow          = "Europe(Moscow)"
//+ na-ashburn         = "US East(Virginia)"
//+ na-siliconvalley   = "US West(Silicon Valley)"
//+ na-toronto         = "North America(Toronto)"
//+ sa-saopaulo        = "South America(São Paulo)"